name: craft-sdk
version: '0.1'
summary: Prebuilt craft dependencies for use as a build-snap
description: |
  This snap contains prebuilt wheels for the pydantic Python library.
  It can be used as a build-snap to provide pydantic to other snaps
  at build time.

base: core24
confinement: strict

parts:
  rust-deps:
    plugin: nil
    build-packages:
      # We suspect that rust 1.90+ new linker uses too much memory,
      # which hangs armhf on launchpad
      # ref: https://blog.rust-lang.org/2025/09/01/rust-lld-on-1.90.0-stable/
      - cargo-1.89
      - rustc-1.89
    override-build: |
      # We need newer versions of cargo and rustc than the default 'cargo'
      # and 'rustc' packages provide, but they don't set the `cargo`
      # and `rustc` commands needed by maturin.
      # These commands specifically allow pydantic-core to build using the
      # non-default rust.
      mkdir -p "${CRAFT_PART_INSTALL}/bin"
      ln -s $(which cargo-1.89) "${CRAFT_PART_INSTALL}/bin/cargo"
      ln -s $(which rustc-1.89) "${CRAFT_PART_INSTALL}/bin/rustc"
    prime:
      - -*

  pydantic-wheel:
    plugin: nil
    source: https://github.com/pydantic/pydantic
    source-type: git
    source-tag: v2.8.2
    after:
      - rust-deps
    build-packages:
      - python3-pip
    override-build: |
      python3 -m pip wheel --no-binary ":all:" --wheel-dir "$CRAFT_PART_INSTALL/wheels/" "$CRAFT_PART_SRC"
    stage:
      - wheels/**
    prime:
      - wheels/**
